spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/final_project_db
    username: alexey
    password: Metallica1983
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        types.print.banner: false
      open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080